### PR TITLE
E accuracy improvmen

### PR DESCRIPTION
**Pull request by EmWhyy**
detect_plates:
Takes an image runs the original yolo model to detect car boxes, takes the coordinates of these boxes.
Runs our plate recognition on the car boxes. Takes the coordinates of the plate and transforms it back to the main picture.
In the end you get an array with the coordinates of the licence plates. 
We can also filter all boxes out if their confidence level is to low:  `conf_interval`

- Which form is the image and how do we process it 
- what should be the output for this function? 
- should we init car_class_id in the __init__

In this branch is also the blur function:  #23
image

### CODE REVIEW

**Comment by TheDying0fLight** [comment]
Hab jetzt erst gesehen das du noch gar keine Reviews requested hast. Solltest du machen falls du bereit bist. Habs jetzt trotzdem reviewed

**Review by TheDying0fLight — CHANGES_REQUESTED** [review]
See e442034d1b90122e3f53bec2ce06167bd2d3a6f6 (made a branch)

**Comment by EmWhyy** [comment]
PR handled in #28

**Review by TheDying0fLight — APPROVED** [review]
LGTM

**Pull request merged**
